services:
  postgres-prime:
    image: mysql
    container_name: mysql-prime
    ports:
      - "3306:3306"
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: prime_dev
    extends:
      file: common-config.yml
      service: network-deploy-service

networks:
  prime-network:
    driver: "bridge"


