server:
  port: 8080
spring:
  application:
    name: prime-project
  profiles:
    active: dev

#Spring doc
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    version: OPENAPI_3_0


