services:
  network-deploy-service:
    networks:
      - "prime-network"
    # Active profile
    environment:
      SPRING_PROFILES_ACTIVE: dev
  
  # Common Config server
  microservice-config-server-config:
    extends:
      service: network-deploy-service
    environment:
      # Database
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-prime:3306/prime_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=30000&socketTimeout=30000&wait_timeout=28800
      SPRING_FLYWAY_URL: jdbc:mysql://mysql-prime:3306/prime_dev
      SPRING_DATASOURCE_USERNAME: prime
      SPRING_DATASOURCE_PASSWORD: prime
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 5
      SPRING_FLYWAY_ENABLED: true
      # Eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://prime-be-eureka:8761/eureka/
      # Security
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://prime-be-user:8070
      CUSTOM-SECURITY_ISSUER: http://prime-be-user:8070
      CUSTOM_SECURITY_OAUTH2URL: http://prime-be-user:8070

  #  Only use it in eureka
  microservice-config-eureka-config:
    extends:
      service: network-deploy-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://prime-be-eureka:8761/eureka/