spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000  # Sets HTTP client connection timeout to 1000ms (1 second)
        response-timeout: 2s  # Sets the maximum response wait time to 2 seconds
    globalcors:
      cors-configurations:
        '[/**]': # Applies to all paths
          allowedOrigins: "*"
          allowedMethods: GET, POST, PUT, DELETE, OPTIONS
          allowedHeaders: "*"
          allowCredentials: true

# Eureka Client Configuration
eureka:
  preferIdAddress: true  # Prefers using instance IP address instead of hostname when communicating with Eureka
  client:
    fetchRegistry: true  # Enables fetching service registry information from Eureka
    registerWithEureka: true  # Registers this service with Eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server for service registration & discovery

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
