package com.prime.constants;

/**
 * Description: Define ALl Error Messages
 */
public enum MessageErrors {
    UNAUTHORIZED,
    USER_SERVER_ERROR,
    PAGE_INVALID,
    SIZE_INVALID,
    USER_UNAUTHORIZED,
    ACCOUNT_USERNAME_OR_PASS_INVALID,
    PRODUCT_INVALID,
    PRODUCT_ID_NOT_FOUND,
    PRODUCT_NAME_INVALID,
    PRODUCT_DESCRIPTION_INVALID,
    USER_INVALID,
    USER_NOT_EXISTS,
    USER_NAME_INVALID,
    USER_NAME_NOT_FOUND,
    USER_NAME_EXISTS,
    USER_PASSWORD_INVALID,
    USER_EMAIL_INVALID,
    USER_EMAIL_EXISTS,
    TASK_INVALID,
    TASK_NOT_EXISTS,
    TASK_TITLE_INVALID,
    TASK_DESCRIPTION_INVALID,
    TASK_USER_NAME_INVALID;

}
