management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposes all available Spring Boot Actuator endpoints
  health:
    readiness-state:
      enabled: true  # Enables readiness probes (useful for Kubernetes)
    liveness-state:
      enabled: true  # Enables liveness probes (useful for Kubernetes)
  endpoint:
    health:
      probes:
        enabled: true  # Ensures health probes are enabled
  metrics:
    tags:
      application: ${spring.application.name}  # Adds application name as a tag for metrics

# Logging Configuration
#logging:
#  config: classpath:logback-spring.xml
#  level:
#    root: INFO
#    com.prime: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.web: INFO
#    org.hibernate: INFO
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#  logback:
#    rollingpolicy:
#      max-file-size: 10MB
#      max-history: 30
#      total-size-cap: 1GB